name: randomtalk

include:
  - "web.docker-compose.yml"

networks:
  randomtalk-network:
    driver: bridge

services:
  matchmaker:
    image: randomtalk-matchmaker:local
    working_dir: /app
    entrypoint: ["air", "-c", "/app/deployments/docker/matchmaker/.air.toml"]
    build:
      context: ../../
      dockerfile: ./deployments/docker/matchmaker/debug.Dockerfile
    ports:
      # grpc api
      - "50000:50000"
      # debug port
      - "40000:40000"
    env_file:
      - ./.env.default
    volumes:
      - ../../go.mod:/app/go.mod
      - ../../go.sum:/app/go.sum
      - ../../go.work:/app/go.work
      - ../../go.work.sum:/app/go.work.sum
      - ../../cmd:/app/cmd
      - ../../deployments/docker:/app/deployments/docker
      - ../../justfile:/app/justfile
      - ../../internal:/app/internal
      - ../../proto:/app/proto
    networks:
      - randomtalk-network

  chat:
    image: randomtalk-chat:local
    working_dir: /app
    entrypoint: ["air", "-c", "/app/deployments/docker/chat/.air.toml"]
    build:
      context: ../../
      dockerfile: ./deployments/docker/chat/debug.Dockerfile
    ports:
      # grpc api
      - "51000:51000"
      # debug port
      - "41000:41000"
    env_file:
      - ./.env.default
    volumes:
      - ../../go.mod:/app/go.mod
      - ../../go.sum:/app/go.sum
      - ../../go.work:/app/go.work
      - ../../go.work.sum:/app/go.work.sum
      - ../../cmd:/app/cmd
      - ../../deployments/docker:/app/deployments/docker
      - ../../justfile:/app/justfile
      - ../../internal:/app/internal
      - ../../proto:/app/proto
    networks:
      - randomtalk-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # For OpenTelemetry gRPC traces
      - "14268:14268" # For OpenTelemetry HTTP traces
      - "4317:4317" # For gRPC traces
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 # Optional: Zipkin-compatible endpoint
    networks:
      - randomtalk-network
