name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      jetstream:
        image: nats:alpine
        options: --name jetstream
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
      - name: Install Just
        run: sudo apt-get update && sudo apt-get install -y just
      - name: Build
        run: just go-build
      - name: Run unit tests
        run: just go-tests
      - name: start_jetstream
        run: |
          chmod a+x ${{ github.workspace }}/.github/workflows/jetstream-entrypoint.sh
          docker cp ${{ github.workspace }}/.github/workflows/jetstream-entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
          docker restart jetstream
          sleep 10 # Wait for JetStream to start
      - name: Run integration tests
        run: just go-integration-tests
