name: Go CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: go-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      jetstream:
        image: nats:alpine
        ports:
          - 4222:4222
          - 8222:8222
        options: --name jetstream
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - '**.go'
      - name: Set up Go
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          check-latest: true
          cache-dependency-path: internal/**/go.sum
      - name: Install Just
        if: steps.changes.outputs.src == 'true'
        run: sudo apt-get update && sudo apt-get install -y just
      - name: Build
        if: steps.changes.outputs.src == 'true'
        run: just go-build
      - name: Run unit tests
        if: steps.changes.outputs.src == 'true'
        run: just go-tests
      - name: start_jetstream
        if: steps.changes.outputs.src == 'true'
        run: |
          chmod a+x ${{ github.workspace }}/.github/workflows/jetstream-entrypoint.sh
          docker cp ${{ github.workspace }}/.github/workflows/jetstream-entrypoint.sh jetstream:/usr/local/bin/docker-entrypoint.sh
          docker restart jetstream
      - name: Sleep for JetStream to start
        if: steps.changes.outputs.src == 'true'
        run: sleep 10
      - name: Run integration tests
        if: steps.changes.outputs.src == 'true'
        run: just go-integration-tests
